#!/bin/bash
mkdir -p ~/.vim/autoload
git clone https://github.com/junegunn/vim-plug.git #vim-plug
cp vim-plug/plug.vim ~/.vim/autoload/
cp .vimrc ~/ 
rm -rf vim-plug
os=$(uname -a)
if [ "$os" =~ "arch" ];then
	pacman -Sy ctags
elif [ "$os" =~ "ubuntu" ]||[ "$os" =~ "debian" ];then
	apt install ctags -y
elif [ "$os" =~ "centos" ];then
	yum install ctags -y
fi	
